import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Manage | Landing Page',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-be-vietnam-pro antialiased overflow-x-hidden">
        {children}
      </body>
    </html>
  );
}
